apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sftp-netdirector-user-management
  title: user on sftp.netdirector.auto
  description: Create a new user on sftp.netdirector.auto by providing username, bucket, target path and optional password.
spec:
  owner: guests
  type: service
  definitions:
    enumTemplates:
      enum: &enumActions
        - Create User
        - Delete User
        - Get User
  parameters:
    - title: Choose action and complete the form
      ui:order:
        - action
        - sftpusername
        - sftpbucketname 
        - sftpbucketpath
        - sftptargetpath
        - sftppassword
      properties:
        action:
          title: User Action
          type: string
          description: What user action do you want to perform?
          enum: *enumActions
      dependencies:
          action:
            allOf:
              - if:
                  properties:
                    action:
                      enum: [Create User]
                then:
                  properties:
                    sftpusername:
                      title: Username
                      type: string
                      description: The username to be created                    
                    sftpbucketname:
                      title: Bucket Name
                      type: string
                      description: The name of the bucket you want to use
                    sftpbucketpath:   
                      title: Bucket Path
                      type: string
                      description: The path you want to use relative to the top level of the bucket. By default the username will be used.
                    sftptargetpath:
                      title: Target Path
                      type: string
                      description: Use default unless you understand this option.
                    sftppassword: 
                      title: Password
                      type: string
                      description: The password of the new user to be created. If not provided, a random password will be generated.
                  required:
                    - sftpusername
                    - sftpbucketname
              - if:
                  properties:
                    action:
                      enum: [Delete User]
                then:
                  properties:
                    sftpusername:
                      title: Usename
                      type: string
                      description: The user to be deleted
                  required:
                    - sftpusername
              - if:
                  properties:
                    action:
                      enum: [Get User]
                then:
                  properties:
                    sftpusername:
                      title: Usename
                      type: string
                      description: The user to be get details for
                  required:
                    - sftbucketname
    - title: Acknowledgement
      properties:
        acknowledgementCheckbox:
          title: I confirm the details I have entered are correct
          type: boolean
          description: Confirm user details are correct
      required:
        - acknowledgementCheckbox
  steps:
    - id: dispatch
      name: Start create user workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=ceeb0t&repo=github-workflow-testing
        workflowId: add-sftp-user.yaml
        branchOrTagName: main
        workflowInputs:
          nd_sftp_username: ${{ parameters.sftpusername }}
          nd_sftp_bucketname: ${{ parameters.sftpbucketname }}
          nd_sftp_targetpath: ${{ parameters.sftptargetpath }}
          nd_sftp_bucketpath: ${{ parameters.sftpbucketpath }}
          nd_sftp_password: ${{ parameters.sftppassword }}
  #   - id: workflow
  #     name: Get Workflow URL
  #     action: ceeb0t:github:workflow:url
  #     input:
  #       owner: ceeb0t
  #       repo: repo=github-workflow-testing
  #       workflowId: add-sftp-user.yaml
  #       waitForCompletion: true
  #       waitDelaySeconds: 15
  output:
    links:
      - title: View Creation Workflow
        url: ${{ steps.workflow.output.url }}