apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sftp-netdirector-user-management
  title: Manage User on sftp.netdirector.auto
  description: Create, Delete or retrieve user information for sftp.netdirector.auto
spec:
  owner: phoenix
  type: create
  definitions:
    enumTemplates:
      enum: &enumActions
        - Create User
        - Delete User
        - Get User
  parameters:
    - title: Choose action and complete the form
      ui:order:
        - action
        - sftpusername
        - sftpbucketname 
        - sftpbucketpath
        - sftptargetpath
        - sftppassword
      properties:
        owner:
          type: string
          default: keyloop-platform
          backstage:featureFlag: hide-hiddenParam
        repo:
          type: string
          default: internal_devops_sftp-netdirector-user-management
          backstage:featureFlag: hide-hiddenParam
        action:
          title: User Action
          type: string
          description: What user action do you want to perform?
          enum: *enumActions
      dependencies:
        action:
          allOf:
            - if:
                properties:
                  action:
                    enum: [Create User]
              then:
                properties:
                  sftpusername:
                    title: Username
                    type: string
                    description: The username to be created                    
                  sftpbucketname:
                    title: Bucket Name
                    type: string
                    description: The name of the bucket you want to use
                  sftpbucketpath:   
                    title: Bucket Path
                    type: string
                    description: The path you want to use relative to the top level of the bucket. By default the username will be used.
                  sftptargetpath:
                    title: Target Path
                    type: string
                    description: Use default unless you understand this option.
                  sftppassword: 
                    title: Password
                    type: string
                    description: The password of the new user to be created. If not provided, a random password will be generated.
                required:
                  - sftpusername
                  - sftpbucketname
            - if:
                properties:
                  action:
                    enum: [Delete User]
              then:
                properties:
                  sftpusername:
                    title: Username
                    type: string
                    description: The user to be deleted
                required:
                  - sftpusername
            - if:
                properties:
                  action:
                    enum: [Get User]
              then:
                properties:
                  sftpusername:
                    title: Username
                    type: string
                    description: The user to get details for
                required:
                  - sftpusername
    - title: Acknowledgement
      properties:
        acknowledgementCheckbox:
          title: I confirm the details I have entered are correct
          type: boolean
          description: Confirm user details are correct
      required:
        - acknowledgementCheckbox
  steps:
    - id: dispatch-create
      name: Start create user workflow
      if: ${{ parameters.action == 'Create User' }}
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        workflowId: add-sftp-user.yaml
        branchOrTagName: main
        workflowInputs:
          nd_sftp_username: ${{ parameters.sftpusername }}
          nd_sftp_bucketname: ${{ parameters.sftpbucketname }}
          nd_sftp_targetpath: ${{ parameters.sftptargetpath }}
          nd_sftp_bucketpath: ${{ parameters.sftpbucketpath }}
          nd_sftp_password: ${{ parameters.sftppassword }}
    - id: dispatch-delete
      name: Start delete user workflow
      if:  ${{ parameters.action == 'Delete User' }}
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        workflowId: del-sftp-user.yaml
        branchOrTagName: main
        workflowInputs:
          nd_sftp_username: ${{ parameters.sftpusername }}
    - id: dispatch-get
      name: Start get user workflow
      if:  ${{ parameters.action == 'Get User' }}
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        workflowId: get-sftp-user.yaml
        branchOrTagName: main
        workflowInputs:
          nd_sftp_username: ${{ parameters.sftpusername }}
    # - id: workflow-create
    #   if: ${{ parameters.action == 'Create User' }}
    #   name: Get Workflow URL
    #   action: keyloop:github:workflow:url
    #   input:
    #     owner: keyloop-platform
    #     repo: internal_devops_sftp-netdirector-user-management
    #     workflowId: add-sftp-user.yaml
    #     waitForCompletion: true
    #     waitDelaySeconds: 15
    # - id: workflow-delete
    #   if: ${{ parameters.action == 'Delete User' }}
    #   name: Get Workflow URL
    #   action: keyloop:github:workflow:url
    #   input:
    #     owner: keyloop-platform
    #     repo: internal_devops_sftp-netdirector-user-management
    #     workflowId: del-sftp-user.yaml
    #     waitForCompletion: true
    #     waitDelaySeconds: 15
    # - id: workflow-get
    #   if: ${{ parameters.action == 'Get User' }}
    #   name: Get Workflow URL
    #   action: keyloop:github:workflow:url
    #   input:
    #     owner: keyloop-platform
    #     repo: internal_devops_sftp-netdirector-user-management
    #     workflowId: get-sftp-user.yaml
    #     waitForCompletion: true
    #     waitDelaySeconds: 15

  output:
    links:
      - title: View Workflow
        url: ${{ steps.workflow-create.output.url }}
      - title: View Delete Workflow
        url: ${{ steps.workflow-delete.output.url }}
      - title: View Get Workflow  
        url: ${{ steps.workflow-get.output.url }}