name: Delete.SFTP.User
on:
  workflow_dispatch:
    inputs:
      nd_sftp_username:
        type: string
        description: User to be deleted
        required: true
jobs:
  delete-sftp-user:
    name: Delete.SFTP.User
    runs-on: ubuntu-latest
    steps:
      - name: Generate MD5 Hash
        run: |
          # Generate the MD5 hash of the username
          USERHASH=$(echo "${{ inputs.nd_sftp_username }}" | rev | tr -d "\n" | md5sum | awk '{print $1}')

          # Check if user exists based on hash
          CHECKEXIST=$(curl -s -X GET https://k6bw01xogf.execute-api.eu-west-1.amazonaws.com/user/$USERHASH | jq -r .Message)

          # If not found, do nothing. If found, delete the user
          echo "userhash=$USERHASH" >> $GITHUB_ENV
          echo "exist=$CHECKEXIST" >> $GITHUB_ENV
      - name: If Exists
        if: ${{ contains(env.exist, 'User not found') }}
        run: echo "User not found" >> $GITHUB_STEP_SUMMARY
      - name: If not exists
        if: ${{ contains(env.exist, 'User found') }}
        run: |            
            HASH=$(curl -s -X GET https://k6bw01xogf.execute-api.eu-west-1.amazonaws.com/user/${{ env.userhash }} | jq -r '.User[].Hash')
            outcome=$(curl -s -X DELETE https://k6bw01xogf.execute-api.eu-west-1.amazonaws.com/user/$HASH | jq -r '.Message')
            echo $outcome >> $GITHUB_STEP_SUMMARY