name: Get user to NetDirector SFTP via Transfer API
on:
  workflow_dispatch:
    inputs:
      nd_sftp_username:
        type: string
        description: Username to be get details for
        required: true
jobs:
  submit-data:
    runs-on: ubuntu-latest
    steps:
      - run: |
          HASH=$(echo "${{ inputs.nd_sftp_username }}" | rev | tr -d "\n" | md5sum | awk '{print $1}')
          curl -s -X GET https://k6bw01xogf.execute-api.eu-west-1.amazonaws.com/user/$HASH | jq .
    env:
        USER_NAME: ${{ inputs.nd_sftp_username }}