name: Merge All JSON Files in configs/ Folder

on:
  workflow_dispatch:

jobs:
  merge-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Merge all JSON files in configs/ folder
      run: |
        # Merge all .json files in the configs/ directory into merged-config.json
        jq -s 'add' configs/*.json > merged-config.json

    - name: Show merged.json result
      run: cat merged-config.json

    - name: Commit and push merged-config.json
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add merged-config.json
        git commit -m "Auto-merged JSON files from configs/"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
