name: Merge All JSON Files in Root

on:
  workflow_dispatch:

jobs:
  merge-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Merge all JSON files in root directory
      run: |
        # Merge all .json files in the root directory into merged.json
        jq -s 'reduce .[] as $item ({}; . * $item)' .github/newrelic/*.json > merged.json

    - name: Show merged.json result
      run: cat merged.json

    - name: Commit and push merged.json
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add merged.json
        git commit -m "Auto-merged JSON files from root"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
